apiVersion: v1
entries:
  zlog-collector:
  - apiVersion: v1
    appVersion: 1.18.0
    created: 2020-03-09T17:54:02.082296056-07:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: 0c09b865c9cf2e0f6e5f9e61b1d0df58c742cdc426a6d5f8685d7df1baa260c1
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-1.18.0.tgz
    version: 1.18.0
  - apiVersion: v1
    appVersion: 1.15.0
    created: 2020-03-09T17:54:02.082009114-07:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: ff44fa7e032b203812a0c99424574ff6109aa16b176057ff7c4b3159ce924528
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-1.15.0.tgz
    version: 1.15.0
generated: 2020-03-09T17:54:02.081437059-07:00
