apiVersion: v1
entries:
  zlog-collector:
  - apiVersion: v1
    appVersion: 1.15.0
    created: 2019-11-16T17:52:45.325602932-08:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: a8b850b86cd19649090336e9fbcb7895449ca62bb4470b3ea950ee5ec0d363f2
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-1.15.0.tgz
    version: 1.15.0
generated: 2019-11-16T17:52:45.325331511-08:00
