apiVersion: v1
entries:
  zlog-collector:
  - apiVersion: v1
    appVersion: 1.18.0
    created: 2020-04-11T16:17:23.138835153-07:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: 69c66d296fbfc22c04df3a68eccf0b68f00983a1852b16f91db398ae70e6ea0a
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-1.18.0.tgz
    version: 1.18.0
  - apiVersion: v1
    appVersion: 1.18.0
    created: 2020-04-11T16:17:23.139171055-07:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: e432512db347a6c01c6566cb9f7427bbec3dfd4cd4e5122534c5f21f236caace
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-buffer.tgz
    version: 1.18.0
  - apiVersion: v1
    appVersion: 1.15.0
    created: 2020-04-11T16:17:23.138520798-07:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: ff44fa7e032b203812a0c99424574ff6109aa16b176057ff7c4b3159ce924528
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-1.15.0.tgz
    version: 1.15.0
generated: 2020-04-11T16:17:23.138092934-07:00
