apiVersion: v1
entries:
  zlog-collector:
  - apiVersion: v1
    appVersion: 1.11.0
    created: 2019-10-30T11:35:26.006919549-07:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: 40914a1fa4479ff2a8dfb4095a39f434b862bd3565af16314547a1515678cf8c
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-1.11.0.tgz
    version: 1.11.0
generated: 2019-10-30T11:35:26.006673666-07:00
