apiVersion: v1
entries:
  zlog-collector:
  - apiVersion: v1
    appVersion: 1.39.0
    created: 2020-08-28T13:20:22.327616553-07:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: da4e9702868a208a32042a84ae09f10a13ea332f09c24bbf30ffd7adbde3ef09
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://github.com/zebrium/ze-kubernetes-collector/releases/download/1.39.0/zlog-collector-1.39.0.tgz
    version: 1.39.0
generated: 2020-08-28T13:20:22.327223377-07:00
