image:
  name: zebrium/zlog-collector
  tag: latest
  pullPolicy: Always

# Extra environment variables to set for log collector container
extraEnv: []

zebrium:
  name: zlog-collector
  deployment: "unset"
  collectorUrl: ""
  authToken: ""
  autoupdate: "1"
  verifySSL: "true"
  excludePodRegex: ""
  tailFromHead: "true"
  logFile: ""
  logLevel: "info"
  nodeLogsPath: "/var/log/*.log,/var/log/syslog,/var/log/messages,/var/log/secure"
  excludePath: "[\"/var/log/boot.log\",\"/var/log/lastlog\"]"
  flushInterval: "30s"

secret:
  enabled: true

resources:
  requests:
    cpu: 20m
    memory: 500Mi
  limits:
    cpu: 1000m
    memory: 1Gi

updateStrategy: OnDelete

daemonset:
  # Allow the DaemonSet to schedule on tainted nodes
  tolerations: []
  # Deploy on selected nodes
  nodeSelector: {}
  priorityClassName: ""
  dnsPolicy: "ClusterFirst"

